# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    deploy: 
        runs-on: ubuntu-latest
        name: Tencent Cloudbase Github Action Example
        steps: 
        - name: Checkout
          uses: actions/checkout@v2
        - name: Deploy static to Tencent CloudBase
          id: deployStatic
          uses: TencentCloudBase/cloudbase-action@v1.1.1
          with: 
            secretId: ${{ secrets.SECRET_ID }}
            secretKey: ${{ secrets.SECRET_KEY }}
            envId: ${{ secrets.ENV_ID }}
            staticSrcPath: public
